services:
  - type: web
    name: threshold-alert-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_VERSION
        value: 18.20.8
      - key: REACT_APP_API_URL
        value: https://threshold-based-alert-management-system.onrender.com/api
      - key: PORT
        value: 10000
